FROM alpine:latest

ADD . /usr/src/spectrum2

RUN apk add --no-cache ca-certificates && \
	apk add --no-cache --virtual .build-deps cmake make gcc g++ musl-dev boost-dev glib-dev protobuf-dev mariadb-dev sqlite-dev postgresql-dev pidgin-dev libev-dev qt5-qtbase-dev qt5-qtdeclarative-dev apr-util-dev automake autoconf libtool git popt-dev curl-dev openssl libevent-dev mercurial json-glib-dev libgcrypt-dev libwebp-dev libgnome-keyring-dev nss-dev && \
	cd /usr/src/ && \

	wget https://github.com/communi/libcommuni/archive/v3.5.0.tar.gz -O libcommuni-3.5.0.tar.gz && \
	tar xfz libcommuni-*.tar.gz && \
	cd libcommuni-* && \
	./configure --prefix=/opt/libcommuni && \
	make && \
	make install && \
	cd .. && \
	rm -rf libcommuni-* && \

	git clone https://github.com/apache/logging-log4cxx.git && \
	cd logging-log4cxx && \
	./autogen.sh && \
	./configure --prefix=/opt/log4cxx && \
	make && \
	make install && \
	cd .. && \
	rm -rf logging-log4cxx && \

	wget https://github.com/jtv/libpqxx/archive/6.4.7.tar.gz && \
	tar xfz 6.4.7.tar.gz && \
	cd libpqxx-* && \
	./autogen.sh && \
	./configure --enable-shared --disable-documentation --prefix=/opt/libpqxx && \
	make && \
	make install && \
	cd .. && \
	rm -rf libpqxx-* && \

	wget https://swift.im/downloads/releases/swift-4.0.2/swift-4.0.2.tar.gz && \
	tar xfz swift-*.tar.gz && \
	cd swift-* && \
	./scons Swiften SWIFTEN_INSTALLDIR=/opt/_swiften /opt/_swiften && \
	cd .. && \
	rm -rf swift-* && \

	cd spectrum2 && \
	cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DLOG4CXX_INCLUDE_DIR=/opt/log4cxx/include -DLOG4CXX_LIBRARIES=/opt/log4cxx/lib/liblog4cxx.so -DSWIFTEN_INCLUDE_DIR=/opt/_swiften/include -DSWIFTEN_LIBRARY=/opt/_swiften/lib -DSWIFTEN_CONFIG_EXECUTABLE=/opt/_swiften/bin/swiften-config -DPQXX_INCLUDE_DIR=/opt/libpqxx/include -DPQXX_LIBRARY=/opt/libpqxx/lib/libpqxx.so -DPQ_LIBRARY=/opt/libpqxx/lib/libpqxx.so -DQT_INCLUDE_DIR=/opt/libcommuni/include -DQT_LIBRARY_DIR=/opt/libcommuni/lib -DIRC_MODEL_LIBRARY=/opt/libcommuni/lib/libIrcModel.so && \
	make && \
	make test
