name: Publish

on: 
  push:
    branches: 
      - master
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: docker/build-push-action@v1
      env:
        DOCKER_BUILDKIT: 1
      with:
        username: ${{ secrets.DOCKERHUB_LOGIN }}
        password: ${{ secrets.DOCKERHUB }}
        repository: spectrum2/spectrum
        tag_with_ref: true
        target: production
